### ISSUE TITLE
Define API compatibility story

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#109] opened 2019-06-12 00:26 UTC
We need to define the API compatibility story, particularly:
- How OpenTelemetry API evolves over time, what changes are allowed and how they should be made, how breaking and non-breaking changes are handled.
- How we ensure third party libraries that are instrumented using old OpenTelemetry versions remain usable after the API changes.
- How we ensure interoperability of application code and of multiple third party libraries that are instrumented using different OpenTelemetry versions.

**Comment by tigrannajaryan** [comment] 2019-06-12 00:27
@SergeyKanzhelev please assign this to me, I will write the spec.

**Comment by tedsuo** [comment] 2019-07-11 21:19
Closing as a duplicate of #129 and #128. Please reopen if you feel that this is a separate issue.

**Closed by tedsuo** 2019-07-11 21:19 UTC
Labels: area:API
