### ISSUE TITLE
"Semantic Conventions for System Metrics" uses outdated metric instrument types

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-specification#1749] opened 2021-06-09 15:56 UTC
The [Semantic Conventions for System Metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/a5d34467b954866ffff90a1c0ef29a43a040b961/specification/metrics/semantic_conventions/system-metrics.md) document uses the outdated names for instrument types (SumObserver, ValueObserver...). It should be updated to the new metrics API.

**Comment by arminru** [comment] 2021-07-05 13:37
Duplicate of #1788 which has a broader scope.

Thanks for bringing it up @mx-psi!

**Closed by arminru** 2021-07-05 13:37 UTC
Labels: area:semantic-conventions, bug, spec:metrics
