### ISSUE TITLE
Do we really need "branch must be up to date" restriction?

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#936] opened 2020-09-09 17:52 UTC
#931 is approved, but I, as admin, cannot merge it, nor can I merge master to make it pass this check.

cc @open-telemetry/technical-committee

**Comment by Oberon00** [comment] 2020-09-09 17:59
Duplicate of #512

**Comment by carlosalberto** [comment] 2020-09-09 18:05
+1 on this, as it creates too much hassle (but IIRC @bogdandrutu had a reason to enable this).

**Comment by Oberon00** [comment] 2020-09-09 18:14
@yurishkuro I updated the PR in question (I have access to that Dynatrace repository)

**Comment by yurishkuro** [comment] 2020-09-09 18:32
The reasoning in #512 is

> Because we fixed the lint check (broken for 2 months) and started to merge PRs that did not pass the lint check (based on master commit that did not include the fix). This was the only option to enforce that everyone pass the lint check.

I am not convinced it's a good reason, more a reaction to one time issue where bad commits were made due to lack of lint enforcement.

**Comment by Oberon00** [comment] 2020-09-09 18:33
IMHO fixing the lint with quick follow-up PRs on master is easier than pinging people to update their PRs with organization-owned repos.

**Comment by carlosalberto** [comment] 2020-09-11 12:10
Agreed that we should perhaps revert this. @bogdandrutu You ok with that? ;)

**Comment by andrewhsu** [comment] 2020-09-11 15:40
From the issue triage mtg today, if @open-telemetry/technical-committee can either execute this requested change or close this issue.

**Comment by carlosalberto** [comment] 2020-09-11 15:56
cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment] 2020-09-11 16:04
I'm ok reverting it. It's easier to fix issue than block PR merges

**Closed** 2020-09-11 16:06 UTC
Labels: area:miscellaneous, spec:miscellaneous
