### ISSUE TITLE
Why do we need @Nullable Boolean hasRemoteParent in shouldSample?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#79] opened 2019-06-07 06:02 UTC

**Comment by songy23** [comment] 2019-06-07 16:47
To support `always-parent` sampler, which I remember may become the default sampler.

**Comment by bogdandrutu** [comment] 2019-06-07 17:02
Not needed for the moment I think.

**Comment by bogdandrutu** [comment] 2019-08-16 21:28
Closing this as a duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/164

**Closed by bogdandrutu** 2019-08-16 21:28 UTC
Labels: area:API, sampling
