### ISSUE TITLE
The default network port is 4317 for both OTLP/gRPC and OTLP/HTTP

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-specification#1835] opened 2021-07-28 00:04 UTC
**What are you trying to achieve?**

The default port for both [OTLP/gRPC](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-default-port) and [OTLP/HTTP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-default-port) is 4317. This could be cause some inconvenience for service which host both endpoints (like [OTel Collector](https://github.com/open-telemetry/opentelemetry-collector)), as it then requires one of the endpoint to be customer configured.

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by iNikem** [comment] 2021-07-28 06:51
Duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/1816#issuecomment-884253345 ?

**Closed** 2021-08-03 08:05 UTC
Labels: spec:protocol
