### ISSUE TITLE
Define a specification for the OpenTelemetry Logging API and SDK 

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-specification#1258] opened 2020-11-23 18:47 UTC
**What are you trying to achieve?**

Currently there is no logging specification for the API and SDK, similar to specification of the [traces API](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md) and [traces SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md). This means that a large component of the logging functionality is being based off what is specified for traces, which can introduce problems for logs.

**What did you expect to see?**

The logging specification should state the required classes, the methods present for each class, and lay out the logic of the sampler. It should include the classes and the methods of LoggerProvider, Logger, Log Processor and Log Exporter interface. There could be a duplication with the implementation logic between with the Logs and Traces specification, such as  LoggerProvider having the duplicate logic to the TracerProvider, the LogProcessor having similar logic to the SpanProcessor and Log Exporter having similar logic to the SpanExporter, for both the API and SDK. 

Having a well-defined logging specification will allow future additions to the logging API and SDK have a place to reside. Having these documents would help language libraries provide a consistent implementation of logging that satisfies the OpenTelemetry requirements.

**Additional context (Add any other context about the problem here. If you followed an existing documentation, please share the link to it.)**

Currently, the main sources of reference in the specification for logs is limited to a [logging overview](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/logs/overview.md) and [Log Data Model](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/logs/data-model.md) definition. 

cc: @xukaren @MarkSeufert

**Comment by tigrannajaryan** [comment] 2021-02-16 14:50
This is at least partially a duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/894

**Comment by tigrannajaryan** [comment] 2021-03-16 18:24
OTEP 0150 for Logging SDK spec submitted: https://github.com/open-telemetry/oteps/pull/150

**Comment by tigrannajaryan** [comment] 2021-04-23 16:03
OTEP 0150 is approved and merged and is considered to be the specification for now. 

Further refinements and formal merging of the OTEP to the spec documents will be done after prototype implementations.

**Closed by tigrannajaryan** 2021-04-23 16:03 UTC
Labels: release:after-ga, spec:logs
