### ISSUE TITLE
Semantic versions for milestones

### ISSUE THREAD

**Issue by mayurkale22** [open-telemetry/opentelemetry-specification#276] opened 2019-09-30 22:44 UTC
For the defined [milestones](https://github.com/open-telemetry/opentelemetry-specification/blob/master/milestones.md#milestones), the semantic version of library release is not mentioned. I think we should add version numbers to make things consistent across the languages.

For example,

Release | Version | Patch 1 | Patch 2 | Patch n 
-------- | -------- |-------- |-------- |-------- |
 Alpha v0.2 | `0.2.0` | `0.2.1` | `0.2.2` | `0.2.n`|
 Alpha v0.3 | `0.3.0` | `0.3.1` | `0.3.2` | `0.3.n`|
 Alpha v0.4 | `0.4.0` | `0.4.1` | `0.4.2` | `0.4.n`|
 Beta v0.5 | `0.5.0` | `0.5.1` | `0.5.2` | `0.5.n`|
GA v1.0| `1.0.0` | `1.0.1` | `1.0.2` | `1.0.n`|

Also, are we planning to keep API and SDK on the same versions? What if I changed (patch) the SDK, but not API? Should we still release API package with a new version?

Any thoughts?

**Comment by c24t** [comment] 2019-09-30 23:28
One problem with this table that it ignore language-specific conventions for version numbers. For example, python has [special semantics for pre-release versions](https://www.python.org/dev/peps/pep-0440/#pre-releases). We were planning to [release python as `0.1a.0`](https://github.com/open-telemetry/opentelemetry-python/pull/190), but can change this if we're trying to keep all clients in sync.

**Comment by c24t** [comment] 2019-09-30 23:40
> Also, are we planning to keep API and SDK on the same versions? What if I changed (patch) the SDK, but not API? Should we still release API package with a new version?

I wonder the same thing. If we're following major/minor/patch semantics, I'd assume that either package could get a patch update without affecting the other. Major and minor updates to the API would require a major or minor update to the SDK (or the SDK would need to depend on an old version of the API), but not vice-versa.

Another question is whether we're trying to keep the version of the clients in sync with the spec version. https://github.com/open-telemetry/opentelemetry-specification/blob/master/milestones.md#milestones seems to assume that we will, but that would mean that we can't release new major versions of clients without a corresponding major spec version change.

**Comment by tigrannajaryan** [comment] 2019-09-30 23:42
This is related to https://github.com/open-telemetry/opentelemetry-specification/issues/246 and this proposal https://github.com/open-telemetry/opentelemetry-specification/pull/115

You may want to comment on the original issue and review the proposal.

**Comment by tedsuo** [comment] 2019-10-01 00:12
I haven't reviewed the other proposals in a while (looking now), but a quick two cents to get python unstuck:

**High level description of our versioning (proposed)**
* Use a semver like schema - vX.Y.Z
* The highest-order position mush match the spec. For pre-1.0, this means that `v0.2.x` release of an API or SDK package must match `v0.2` of the spec.
* Lower-order positions have no special meaning or relationship. So if you have a `v0.2.x` API and a `v02.y` SDK, `x` and `y` do not need to correlate in any way.
* If a language has a special versioning scheme, that is fine provided that it does not impede or confuse any of the above requirements. A `v0.2a.1` release of python can clearly match a `v0.2` spec, so this is not a problem. However, if there is no special value in diverging from our chosen schema (AKA package managers do not actually care), then the original schema should always be used.

**Comment by tigrannajaryan** [comment] 2019-10-01 00:21
@tedsuo please have a look at https://github.com/open-telemetry/opentelemetry-specification/issues/246

I think what you suggest was already suggested and drawbacks discussed. It would be great if you have ideas on how to overcome the drawbacks.

**Comment by c24t** [comment] 2019-10-01 00:29
Thanks @tedsuo.

> * The highest-order position mush match the spec. For pre-1.0, this means that `v0.2.x` release of an API or SDK package must match `v0.2` of the spec.

I think we're going to run into a problem similar to #246 here. Where #246 describes the relationship between the SDK and API *spec* version, here the problem is between the API package version and API spec version. Following this would mean that we couldn't release major/minor updates to API packages without a corresponding spec change. I'll comment on #246 in detail.

> * A `v0.2a.1` release of python can clearly match a `v0.2` spec, so this is not a problem

For now we can release as `0.1a.0` since this doesn't preclude other versioning schemes. We just can't release a `0.1b.x` or `0.2a.x` without settling on a version labeling schema.

> * if there is no special value in diverging from our chosen schema...

I agree, it sounds like we're ultimately going to call this `0.1.0` in all languages.

**Comment by bruno-garcia** [comment] 2019-10-01 07:54
Second @c24t that although it's great to align these things, it comes with the cost of not being idiomatic. In .NET a alpha/beta/preview package would have something append to the version, i.e:

Preview: `1.0.0-alpha`.
Non preview: `1.0.0` or `1.0.0.0`.

I wouldn't be surprised if tools check if id matches something like `^\d+(\.\d+){1,3}$`

**Comment by bogdandrutu** [comment] 2019-10-10 18:51
This issue was resolved in #280

**Closed by bogdandrutu** 2019-10-10 18:51 UTC
