### ISSUE TITLE
Are there semantic conventions for metrics?

### ISSUE THREAD

**Issue by yangd102** [open-telemetry/opentelemetry-specification#518] opened 2020-03-18 03:46 UTC
Are there semantic conventions for metrics? For example for backend calls (rpc, http, apis etc) could have a general metric of the form. This doesn't make much of a difference if you only do gRPC, however if there are several types of ways to do backend calls, should there be a set of lowest common denominator metrics that everyone can use?

```
opentelemetry.io/server/count { name, status }
opentelemetry.io/server/latency { name, status }

opentelemetry.io/client/count { name, status }
opentelemetry.io/client/latency { name, status }
```

**Comment by jmacd** [comment] 2020-03-18 16:40
Metrics should use the same semantic conventions that spans and resources do. Are there any missing conventions?

**Comment by bogdandrutu** [comment] 2020-06-12 16:28
Duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/651

**Closed by bogdandrutu** 2020-06-12 16:28 UTC
Labels: spec:metrics
