### ISSUE TITLE
OpenTelemetry does not support resetting in-memory Metric to clean the memory usage

### ISSUE THREAD

**Issue by valiparsa** [open-telemetry/opentelemetry-specification#3788] opened 2023-12-13 09:43 UTC
This issue was initially created in the [open-telemetry/opentelemetry-go/issues#4752](https://github.com/open-telemetry/opentelemetry-go/issues/4752) but it was suggested to open a new issue in this repository first.

**What are you trying to achieve?**

We are using [Kyverno](https://github.com/kyverno/kyverno) as a Policy engine in the Kubernetes environment in our product. We often see an increase in the memory consumption of the Kyverno pod due to collected in-memory metrics which have high cardinality due to many labels.

Up-to and including `release-1.7` of Kyverno it was using the Prometheus library directly to expose Metrics. Prometheus client library [supports reseting metric vectors](https://pkg.go.dev/github.com/prometheus/client_golang@v1.13.0/prometheus#MetricVec.Reset) which were used by Kyverno to [periodically (configurable period) reset its internal metrics registry to clean its memory usage and footprint associated with metrics](https://github.com/kyverno/kyverno/blob/release-1.7/pkg/metrics/metrics.go#L126-L131). 

As of [release-1.8](https://github.com/kyverno/kyverno/releases/tag/v1.8.0) Kyverno started to support OpenTelemetry. After this transition this feature of reseting internal metrics to clean its memory usage is lost as OpenTelemetry does not allow reseting metrics, which is supported by the underlying Prometheus library.

What did you expect to see?

OpenTelemetry should support reseting the in-memory metric vectors allowing to clean its memory usage. As this is [supported by Prometheus to reset the Metric vectors](https://github.com/kyverno/kyverno/issues/8401#issuecomment-1811924079) and OpenTelemetry is using Prometheus client library hence, it would be very beneficial for us to consume this feature again in the Kyverno project.

**Additional context.**

As mentioned the underlying [Prometheus library supports reseting in-memory Metric vectors](https://github.com/kyverno/kyverno/issues/8401#issuecomment-1811924079) to clean the memory usage.

**Comment by jack-berg** [comment] 2023-12-13 15:45
I believe this is a duplicate of #2232. Can you take a look and if so, close this issue and include the details here on that issue?

**Comment by jack-berg** [comment] 2023-12-13 15:46
Please feel free to re-open if you feel its a different issue.

**Closed by jack-berg** 2023-12-13 15:46 UTC
Labels: spec:metrics
