### ISSUE TITLE
Define metric semantic conventions for RPC

### ISSUE THREAD

**Issue by jgals** [open-telemetry/opentelemetry-specification#1016] opened 2020-09-25 14:50 UTC
**What are you trying to achieve?**
Documented metric semantic conventions for remote procedure calls (RPC).

**What did you expect to see?**
Metric semantic conventions for RPC documented in markdown generated from YAML definitions as per #547.

**Additional context.**
These should be roughly analogous to the trace semantic conventions for RPC [defined here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/rpc.md). For reference, metric semantic conventions for HTTP operations are already [defined here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/http-metrics.md).

**Comment by jgals** [comment] 2020-10-06 17:45
@aabmass would you, or another contributor from Google, be interested in working on a draft PR to help address this issue?

**Comment by Oberon00** [comment] 2020-10-13 10:45
I think this is a duplicate of #522, which was triaged (long ago, I guess) as P2.

**Comment by jsuereth** [comment] 2020-10-26 23:28
I'm taking a look at this this week, can you assign this to me?

**Closed** 2020-11-26 17:06 UTC
Labels: area:semantic-conventions, priority:p2, release:allowed-for-ga, spec:metrics
