### ISSUE TITLE
Define unit change schema transformation rule 

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-specification#4028] opened 2024-05-01 03:09 UTC
**What are you trying to achieve?**

It could be possible to handle unit changes such as e.g. `ms` -> `s` with schema transformation. 

**Additional context.**

https://github.com/open-telemetry/semantic-conventions/pull/966#discussion_r1583742805

**Comment by pyohannes** [comment] 2024-05-02 09:56
This is a duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/3729.

**Closed** 2024-05-02 15:31 UTC
Labels: spec:miscellaneous
