### ISSUE TITLE
Add more metric types

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#126] opened 2019-06-14 22:55 UTC
See this comment: https://github.com/open-telemetry/opentelemetry-specification/pull/121#discussion_r294012431

**Comment by jmacd** [comment] 2019-07-01 17:23
See issue 169

**Comment by tedsuo** [comment] 2019-07-11 21:10
Closing as a duplicate of #146

**Closed by tedsuo** 2019-07-11 21:10 UTC
Labels: area:API
