### ISSUE TITLE
Define the metrics that we expect to capture from RPC integrations

### ISSUE THREAD

**Issue by mtwo** [open-telemetry/opentelemetry-specification#522] opened 2020-03-20 00:26 UTC
_This is out of scope for beta, in scope for RC and beyond_

While we have (somewhat) clear expectations of the spans and annotations that we expect tracing integrations to capture from RPC clients and servers, this isn't the case for metrics integrations. I propose that RPC integrations should capture the following metrics by default:

- Request / response latency, in milliseconds
- Throughput, in queries per second, broken down by status / response code

**Comment by fbogsany** [comment] 2020-03-24 14:41
Errors per second?

**Comment by mtwo** [comment] 2020-03-25 07:03
@fbogsany would queries per second with aggregation by status code (or equivalent) satisfy that?

**Comment by Oberon00** [comment] 2020-03-25 10:59
I think there are many metrics that could be generated on the back end out of the received spans & traces. Duplicating these metrics on the client side might be helpful in case we sample though.

**Comment by mtwo** [comment] 2020-03-27 20:50
@fbogsany edited the issue to specify that QPS metrics should be broken down by status code
@Oberon00 edited the issue to specify that this should be done for clients and servers

**Comment by bogdandrutu** [comment] 2020-10-16 16:06
Closing this as a duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/1016

**Closed by bogdandrutu** 2020-10-16 16:06 UTC
Labels: area:semantic-conventions, priority:p2, release:required-for-ga, spec:metrics
