### ISSUE TITLE
Remove getters for span status

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-specification#1029] opened 2020-09-28 16:15 UTC
**What are you trying to achieve?**
Remove the following methods from the Span interface:
* GetCanonicalCode
* GetDescription

**Additional context.**
 We do not want any getters on spans, as it leads to inconsistent behavior which we do not want users to rely upon. Due to overhead concerns, we do not want the public API to force the underlying implementation to retain any state. Examples of implementations which do no include: 
* no tracer installed
* sampling enabled
* streaming implementations

Examples of cases where getters could bite users:
* Using status to control application behavior. For example, setting trace status to Error, then switching behavior based on checking the status. This will not always work as expected.

If users which to use this information in their application, they can store it as a separate item in the context object (or as baggage), rather than rely on the span itself.

**Comment by Oberon00** [comment] 2020-09-28 17:02
Note that while there are getters for attributes of status, there is no getter on the span for status itself (making them less useful but also less dangerous) -- I'm on board for removing them.

**Comment by bogdandrutu** [comment] 2020-09-28 19:54
> What are you trying to achieve?
Remove the following methods from the Span interface:
GetCanonicalCode
GetDescription

Already done, these are not on the Span interface. Propose closing this issue as working as intended, no getters on the Span interface.

Please open a different issue if this is about getters on the Status object.

**Closed by bogdandrutu** 2020-09-28 19:54 UTC
Labels: area:api, spec:trace

**Comment by tedsuo** [comment] 2020-09-29 15:12
@bogdandrutu are you sure? They are listed right here:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#getcanonicalcode
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#getdescription

**Comment by arminru** [comment] 2020-09-29 16:04
@bogdandrutu @tedsuo I still think it's unclean that we define getters for these two fields in the API but don't even define a `GetStatus` on `Span` to get the `Status` object on which these would be called. I'd be in favor of removing it from the GA version to clean this inconsistency and if there is any need for this, we can always add it back later. If we add it back (or keep it), however, there should also be a `Span.GetStatus` because otherwise it just doesn't make any sense.
