### ISSUE TITLE
Determining OpenTelemetry API Compatibility

### ISSUE THREAD

**Issue by HaloFour** [open-telemetry/opentelemetry-specification#1152] opened 2020-10-28 22:30 UTC
I am working on updating an older tracing library to implement the OpenTelemetry API interfaces.  I was interested in a way to evaluate how "compatible" any given implementation of these APIs would be to the specification.  I recognize that this would be difficult to quantify given that the API basically specifies inputs without outputs so there isn't a way to extract an "actual" result of a trace that could be compared to an expected result.  I am opening this issue to explore this space.

**Comment by arminru** [comment] 2020-11-03 10:38
Duplicate of #1153 (more discussion on there already)

**Closed by arminru** 2020-11-03 10:38 UTC
Labels: area:miscellaneous, priority:p3, release:allowed-for-ga, spec:miscellaneous
