### ISSUE TITLE
Ability to mutate trace state for custom sampling

### ISSUE THREAD

**Issue by narayaruna** [open-telemetry/opentelemetry-specification#854] opened 2020-08-21 17:20 UTC
Use case:
In order to implement one or more custom sampling strategies. For example - control service participation in a trace. Imagine the following topology.

A -> B -> C -> D

- Service A doesn't sample the incoming request however the trace context is initialized and sent downstream with sampling decision set to false.
- Service B is configured to start a trace for all (100% sampling) the requests matching the path /foo. It encodes this sampling decision in the trace state so any downstream services can participate.
- Service C doesn't do anything but propagates the context down.
- Service D is configured to participate in the trace initiated by Service B. It looks up the trace state and makes a sampling decision to record the spans.

Basically the ask is to provide hooks/API changes to support such a use case. Specifically, in this example service B will need access to modify trace state where the sampling decision is taken. Service D will need access to the trace state to make a sampling decision.

@bogdandrutu @tedsuo @anuraaga

**Comment by bogdandrutu** [comment] 2020-08-24 17:35
Duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/856, copied the example there.

**Closed by bogdandrutu** 2020-08-24 17:35 UTC
