### ISSUE TITLE
Rename the protocol to OTELP

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-specification#929] opened 2020-09-07 18:38 UTC
(Sorry for filing a first issue that is a bikeshedding one.)

The OpenTelemetry protocol is shortened as OTLP but  it soudns very similar to OLTP which is a very well-known concept in computer science as in "Online Transactional Processing". In terms of disambiguity and searchability, wouldn't it make sense to name to OTELP?

The spec already strongly discourages to use "OT" for OpenTelemetry due to ambiguity with OpenTracing and suggest "OTel".

Additionally, "OTEL_" is already used as a prefix for environmental variables, see
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md#general-sdk-configuration. Given there is so much consensus on using "OTEL" to refer to OpenTelemetry, the protocol can follow the same convention.

**Comment by carlosalberto** [comment] 2020-09-08 13:57
Marking it as Required for GA, as we either change the name now, or never ;)

**Comment by andrewhsu** [comment] 2020-09-08 15:14
Talked about this at the spec sig mtg today and prioritized as P2 since the desired direction is to just update the marketing and documentation of OTLP to be OTELP.

**Comment by pmm-sumo** [comment] 2020-09-08 15:29
The change would impact user-facing configuration of several components, including:
* [receiver](https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver/otlpreceiver) and [exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter/otlpexporter) in OpenTelemetry Collector
* exporters of client libraries, e.g. [Java Instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation#otlp-exporter), [Go](https://github.com/open-telemetry/opentelemetry-go/tree/master/exporters/otlp), [Python](https://github.com/open-telemetry/opentelemetry-python/tree/master/exporter/opentelemetry-exporter-otlp), [Rust](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-otlp/README.md) and others

**Comment by tedsuo** [comment] 2020-09-08 15:29
I like the disambiguation. My only request is that we pronounce this "Otel-P" and not "O-Telp." 🙏 

More seriously, I want to flag that this is a deeper change than just updating marketing and documentation. There are numerous code changes, especially package names. So this will "break all the things" if we do it.

https://github.com/search?q=org%3Aopen-telemetry+otlp&type=Code

We should put the effort into changing everywhere if we are going to do this.

**Comment by Oberon00** [comment] 2020-09-08 15:46
> My only request is that we pronounce this "Otel-P" and not "O-Telp." 

Should we also spell it as "OTelP"?

**Comment by carlosalberto** [comment] 2020-09-08 16:56
> Should we also spell it as "OTelP"?

If we go with this change,  OTELP is much simpler than OTeLP.

**Comment by tigrannajaryan** [comment] 2020-09-08 18:20
I agree that if we decide to change then we should also change in the source code and in the configs otherwise it will be confusing. It is not just work that we need to do, it also means external people who already use OpenTelemetry will be affected. I know people who use the Collector in production - we will break their configs.

I don't know if it is worth the hassle.

**Comment by tedsuo** [comment] 2020-09-09 01:34
This is neither here nor there, but "consuming a stream of OTel-P" sounds disgusting. I will be making that joke A LOT. :)

In all seriousness though, looking through the ramifications of this change, I am also getting concerned. We are almost to GA, and the collector/OTLP is the most widely used part of OpenTelemetry. I can confirm that it is getting wide adoption at this point - frankly I'm surprised at how many organizations are already running it in production. This will smash a lot of stuff. 

I do understand the searchability concern though. Looking at search results, I see several misspellings of OLTP that rank higher that OTLP. But they look like low quality results, and I imagine OTLP will overtake them in time, once our documentation is finished and properly indexed. "OTLP opentelemetry" is also any easy way to disambiguate. I don't think anyone would do a search for "OTLP" who does not know that it is a part of OpenTelemetry.

@rakyll do these concerns make sense to you? Basically, we are worried that the ship has already sailed.

**Comment by tigrannajaryan** [comment] 2020-09-09 01:41
Another concerns is again about searchability but from a different angle. Even if we rename to OTELP all historical references to OTLP in comments, issues, PR descriptions will stay. Anyone searching for OTELP in the future is going to miss all that unless they know about the name change and also search for OTLP. (I assume no-one intends to go and fix all comments, issues and PRs).

**Comment by mtwo** [comment] 2020-09-11 16:01
While I agree with @rakyll 's concerns, I think that we're too close to RC/GA to feasibly make this change without pushing the schedule back and causing headaches for existing Collector users

**Comment by andrewhsu** [comment] 2020-09-25 15:14
from the issue triage meeting today with TC, closing this because of reasons stated in comment above

**Closed by andrewhsu** 2020-09-25 15:14 UTC
Labels: spec:protocol
